include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - prefer_const_constructors
    - prefer_const_literals_to_create_immutables
    - require_trailing_commas
    - sort_constructors_first
    - sort_unnamed_constructors_first
    - prefer_single_quotes
    - avoid_dynamic_calls
    - avoid_print
    - prefer_final_fields
    - unnecessary_await_in_return
    - use_string_in_part_of_directives
